package khom.pavlo.aitripplanner.ui.strings

import aitripplanner.composeapp.generated.resources.*
import androidx.compose.runtime.Composable
import org.jetbrains.compose.resources.stringResource

data class AppStrings(
    val createTripTab: String,
    val myTripsTab: String,
    val createTripTitle: String,
    val editTripTitle: String,
    val createTripSubtitle: String,
    val editTripSubtitle: String,
    val createTripAction: String,
    val editTripAction: String,
    val languageLabel: String,
    val cityFieldLabel: String,
    val tripTitleFieldLabel: String,
    val summaryFieldLabel: String,
    val heroNoteFieldLabel: String,
    val helperText: String,
    val currentTripTitle: String,
    val currentTripSubtitle: String,
    val currentTripEmptyTitle: String,
    val currentTripEmptySubtitle: String,
    val recentTripsTitle: String,
    val recentTripsSubtitle: String,
    val recentTripsEmptyTitle: String,
    val recentTripsEmptySubtitle: String,
    val savedTripsTitle: String,
    val savedTripsSubtitle: String,
    val savedDeleteFailedTitle: String,
    val savedErrorTitle: String,
    val savedEmptyTitle: String,
    val savedEmptySubtitle: String,
    val dayByDayTitle: String,
    val loadingEditTitle: String,
    val loadingEditSubtitle: String,
    val deleteTripTitle: String,
    val deleteTripMessage: String,
    val deleteAction: String,
    val cancelAction: String,
    val editAction: String,
    val backAction: String,
    val detailsLoadErrorTitle: String,
    val detailsDeleteFailedTitle: String,
    val detailsDeletingTitle: String,
    val detailsDeletingSubtitle: String,
    val detailsEmptyTitle: String,
    val detailsEmptySubtitle: String,
)

@Composable
fun appStrings(): AppStrings = AppStrings(
    createTripTab = stringResource(Res.string.create_trip_tab),
    myTripsTab = stringResource(Res.string.my_trips_tab),
    createTripTitle = stringResource(Res.string.create_trip_title),
    editTripTitle = stringResource(Res.string.edit_trip_title),
    createTripSubtitle = stringResource(Res.string.create_trip_subtitle),
    editTripSubtitle = stringResource(Res.string.edit_trip_subtitle),
    createTripAction = stringResource(Res.string.create_trip_action),
    editTripAction = stringResource(Res.string.edit_trip_action),
    languageLabel = stringResource(Res.string.language_label),
    cityFieldLabel = stringResource(Res.string.city_field_label),
    tripTitleFieldLabel = stringResource(Res.string.trip_title_field_label),
    summaryFieldLabel = stringResource(Res.string.summary_field_label),
    heroNoteFieldLabel = stringResource(Res.string.hero_note_field_label),
    helperText = stringResource(Res.string.helper_text),
    currentTripTitle = stringResource(Res.string.current_trip_title),
    currentTripSubtitle = stringResource(Res.string.current_trip_subtitle),
    currentTripEmptyTitle = stringResource(Res.string.current_trip_empty_title),
    currentTripEmptySubtitle = stringResource(Res.string.current_trip_empty_subtitle),
    recentTripsTitle = stringResource(Res.string.recent_trips_title),
    recentTripsSubtitle = stringResource(Res.string.recent_trips_subtitle),
    recentTripsEmptyTitle = stringResource(Res.string.recent_trips_empty_title),
    recentTripsEmptySubtitle = stringResource(Res.string.recent_trips_empty_subtitle),
    savedTripsTitle = stringResource(Res.string.saved_trips_title),
    savedTripsSubtitle = stringResource(Res.string.saved_trips_subtitle),
    savedDeleteFailedTitle = stringResource(Res.string.saved_delete_failed_title),
    savedErrorTitle = stringResource(Res.string.saved_error_title),
    savedEmptyTitle = stringResource(Res.string.saved_empty_title),
    savedEmptySubtitle = stringResource(Res.string.saved_empty_subtitle),
    dayByDayTitle = stringResource(Res.string.day_by_day_title),
    loadingEditTitle = stringResource(Res.string.loading_edit_title),
    loadingEditSubtitle = stringResource(Res.string.loading_edit_subtitle),
    deleteTripTitle = stringResource(Res.string.delete_trip_title),
    deleteTripMessage = stringResource(Res.string.delete_trip_message),
    deleteAction = stringResource(Res.string.delete_action),
    cancelAction = stringResource(Res.string.cancel_action),
    editAction = stringResource(Res.string.edit_action),
    backAction = stringResource(Res.string.back_action),
    detailsLoadErrorTitle = stringResource(Res.string.details_load_error_title),
    detailsDeleteFailedTitle = stringResource(Res.string.details_delete_failed_title),
    detailsDeletingTitle = stringResource(Res.string.details_deleting_title),
    detailsDeletingSubtitle = stringResource(Res.string.details_deleting_subtitle),
    detailsEmptyTitle = stringResource(Res.string.details_empty_title),
    detailsEmptySubtitle = stringResource(Res.string.details_empty_subtitle),
)
